/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class keobuabao extends javax.swing.JFrame {

    /**
     * Creates new form game1
     */
    public keobuabao() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblNguoiThang.setVisible(false);//ẩn hình
        lblMayThang.setVisible(false);
        lblHoa.setVisible(false);
    }
    private int mayChon;
    private int diemNguoi=0, diemMay=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHoa = new javax.swing.JLabel();
        btnKeo = new javax.swing.JButton();
        btnBua = new javax.swing.JButton();
        bntBao = new javax.swing.JButton();
        lblNguoiThang = new javax.swing.JLabel();
        lblMayThang = new javax.swing.JLabel();
        lblDiemNguoi = new javax.swing.JLabel();
        lblDiemMay = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ONE TWO THREE GAME");
        setMinimumSize(new java.awt.Dimension(995, 634));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ONE TWO THREE GAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(282, 34, 442, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Scorse:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(715, 112, 81, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Scorse:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(141, 111, 81, 29);
        getContentPane().add(lblHien);
        lblHien.setBounds(210, 210, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\may_tinh.png")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 150, 200, 229);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\you.png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(662, 159, 200, 229);

        lblHoa.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\hoa.png")); // NOI18N
        getContentPane().add(lblHoa);
        lblHoa.setBounds(430, 400, 160, 170);

        btnKeo.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\keo.png")); // NOI18N
        btnKeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeoActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeo);
        btnKeo.setBounds(465, 179, 63, 39);

        btnBua.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\bua.png")); // NOI18N
        btnBua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBua);
        btnBua.setBounds(465, 247, 63, 45);

        bntBao.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\bao.png")); // NOI18N
        bntBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBaoActionPerformed(evt);
            }
        });
        getContentPane().add(bntBao);
        bntBao.setBounds(465, 323, 63, 39);

        lblNguoiThang.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\you_win.png")); // NOI18N
        getContentPane().add(lblNguoiThang);
        lblNguoiThang.setBounds(705, 429, 114, 120);

        lblMayThang.setIcon(new javax.swing.ImageIcon("E:\\onjava\\game\\src\\images\\may_win.png")); // NOI18N
        getContentPane().add(lblMayThang);
        lblMayThang.setBounds(190, 430, 120, 120);

        lblDiemNguoi.setText("0");
        getContentPane().add(lblDiemNguoi);
        lblDiemNguoi.setBounds(810, 110, 60, 40);

        lblDiemMay.setText("0");
        getContentPane().add(lblDiemMay);
        lblDiemMay.setBounds(230, 110, 50, 30);

        jMenu1.setText("Thông tin");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hướng dẫn ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Lịch sử");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void GhiFile() throws IOException{
            
        int a = diemMay;
        int b = diemNguoi;
        String chuoi="";
        if(a>b){
            chuoi="May win";
        }
        else
            chuoi ="Nguoi win";
        String dataString = Integer.toString(diemMay)+"\t\t"+ Integer.toString(diemNguoi)+ "\t\t\t"+chuoi+"\n";
        try(FileWriter tw = new FileWriter("LichSuOanTuTi.txt",true)){
            tw.write(dataString);
            tw.close();
        }
    }
    public void KiemTraDieuKienThang() throws IOException{
        int diemNguoi1=Integer.parseInt(lblDiemNguoi.getText());
        int diemMay1=Integer.parseInt(lblDiemMay.getText());
        if(diemNguoi1==10){
            JOptionPane.showMessageDialog(null, "Người thắng");
            GhiFile();
            int kq;
            kq = JOptionPane.showConfirmDialog(null, "bạn đã thắng! bạn có muốn tiếp tục?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION ==kq)
                {                   
                    lblDiemMay.setText("0");
                    lblDiemNguoi.setText("0");
                    lblHien.setIcon(null);
                    diemMay=0;
                    diemNguoi=0;
                    lblNguoiThang.setVisible(false);//ẩn hình
                } else 
                    System.exit(0);  
        }
            
        if(diemMay1==10){
            JOptionPane.showMessageDialog(null, "Máy thắng");
            GhiFile();
            int kq;
            kq = JOptionPane.showConfirmDialog(null, "bạn đã thắng! bạn có muốn tiếp tục?", "Thông báo", JOptionPane.YES_NO_OPTION);
                if(JOptionPane.YES_OPTION ==kq)
                {    
                    lblDiemMay.setText("0");
                    lblDiemNguoi.setText("0");
                    lblHien.setIcon(null);
                    diemMay=0;
                    diemNguoi=0;                  
                    lblMayThang.setVisible(false);
                } else 
                    System.exit(0);
        }
    }
    
    private void bntBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBaoActionPerformed
        // TODO add your handling code here:

        Random rd = new Random();//random
        mayChon = rd.nextInt(3)+1;//gan so ngau nhien tao ra cho may
        
        lblNguoiThang.setVisible(false);
        lblMayThang.setVisible(false);
        lblHoa.setVisible(false);
        
        //người chọn= máy chọn
        if(mayChon==1){
            lblMayThang.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo.png")));
            diemMay++;
        }
        else{
            if(mayChon==2){
            lblNguoiThang.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua.png")));  
            diemNguoi++;
            }
            else{
            lblHoa.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png")));
            }   
        }
        //chuyển đổi từng int sang string
        lblDiemNguoi.setText(Integer.toString(diemNguoi));
        lblDiemMay.setText(Integer.toString(diemMay));
        try {
            KiemTraDieuKienThang();
        } catch (IOException ex) {
            Logger.getLogger(keobuabao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntBaoActionPerformed

    private void btnKeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeoActionPerformed
        // TODO add your handling code here:
        Random rd = new Random();//random
        mayChon = rd.nextInt(3)+1;//gan so ngau nhien tao ra cho may
        
        lblNguoiThang.setVisible(false);
        lblMayThang.setVisible(false);
        lblHoa.setVisible(false);
        
        //người chọn= máy chọn
        if(mayChon==1){
            lblHoa.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo.png")));
        }
        else{
            if(mayChon==2){
            lblMayThang.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua.png")));  
            diemMay++;
            }
            else{
            lblNguoiThang.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png")));
            diemNguoi++;
            }   
        }
        //chuyển đổi từng int sang string
        lblDiemNguoi.setText(Integer.toString(diemNguoi));
        lblDiemMay.setText(Integer.toString(diemMay));
        try {
            KiemTraDieuKienThang();
        } catch (IOException ex) {
            Logger.getLogger(keobuabao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKeoActionPerformed

    private void btnBuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuaActionPerformed
        // TODO add your handling code here:
        
        Random rd = new Random();//random
        mayChon = rd.nextInt(3)+1;//gan so ngau nhien tao ra cho may
        
        lblNguoiThang.setVisible(false);
        lblMayThang.setVisible(false);
        lblHoa.setVisible(false);
        
        //người chọn= máy chọn
        if(mayChon==1){
            lblNguoiThang.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo.png")));
            diemNguoi++;
        }
        else{
            if(mayChon==2){
            lblHoa.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua.png")));  
            }
            else{
            lblMayThang.setVisible(true);
            lblHien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png")));
            diemMay++;
            }   
        }
        //chuyển đổi từng int sang string
        lblDiemNguoi.setText(Integer.toString(diemNguoi));
        lblDiemMay.setText(Integer.toString(diemMay));
        try {
            KiemTraDieuKienThang();
        } catch (IOException ex) {
            Logger.getLogger(keobuabao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuaActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
        HDGameKeoBuaBao a = new HDGameKeoBuaBao();
        a.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        LichSu a = new LichSu();
        a.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(keobuabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(keobuabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(keobuabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(keobuabao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keobuabao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBao;
    private javax.swing.JButton btnBua;
    private javax.swing.JButton btnKeo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDiemMay;
    private javax.swing.JLabel lblDiemNguoi;
    private javax.swing.JLabel lblHien;
    private javax.swing.JLabel lblHoa;
    private javax.swing.JLabel lblMayThang;
    private javax.swing.JLabel lblNguoiThang;
    // End of variables declaration//GEN-END:variables
}
